---

- name: test if userify is installed
  shell: /usr/bin/test -n "$(cat /opt/userify/shim.sh 2> /dev/null)"
  ignore_errors: True
  register: userify_installed

- include: install.yml
  when: userify_installed.rc == 1 and userify_state|default('present') == "present" 

- include: uninstall.yml
  when: userify_installed.rc == 0 and userify_state|default('present') == "absent" 
